"""Discover cameras from the Baseus cloud and serve them over RTSP/HLS/WebRTC.

Writes a runtime credentials file (mode 600) and a generated MediaMTX config,
then launches MediaMTX. Each camera is a MediaMTX path using ``runOnDemand`` so
the P2P bridge only runs while a client is connected -- important for battery
cameras. No secrets are ever written to the repo; only to the runtime dir.
"""
from __future__ import annotations

import json
import os
import shlex
import stat
import sys
from pathlib import Path

from .cloud import BaseusCloud

RUNTIME_DIR = Path(os.environ.get("BASEUS_RUNTIME_DIR", "/run/baseus"))
CAMERAS_FILE = Path(os.environ.get("BASEUS_CAMERAS_FILE", str(RUNTIME_DIR / "cameras.json")))
MEDIAMTX_CFG = Path(os.environ.get("BASEUS_MEDIAMTX_CFG", str(RUNTIME_DIR / "mediamtx.yml")))
MEDIAMTX_BIN = os.environ.get("MEDIAMTX_BIN", "mediamtx")

RTSP_PORT = os.environ.get("BASEUS_RTSP_PORT", "8554")
HLS_PORT = os.environ.get("BASEUS_HLS_PORT", "8888")
WEBRTC_PORT = os.environ.get("BASEUS_WEBRTC_PORT", "8889")
FRAMERATE = os.environ.get("BASEUS_FRAMERATE", "25")
INCLUDE_OFFLINE = os.environ.get("BASEUS_INCLUDE_OFFLINE", "1") not in ("0", "false", "no")


def log(*a):
    print(*a, file=sys.stderr, flush=True)


def _cloud_from_env() -> BaseusCloud:
    return BaseusCloud(
        account=os.environ.get("BASEUS_ACCOUNT", ""),
        password=os.environ.get("BASEUS_PASSWORD", ""),
        region=os.environ.get("BASEUS_REGION", "AUTO"),
        country_code=os.environ.get("BASEUS_COUNTRYCODE", "1"),
    )


def discover() -> list:
    cloud = _cloud_from_env()
    cloud.login()
    cams = cloud.discover_cameras()
    log(f"[cloud] logged in via {cloud.resolved_region}; found {len(cams)} camera(s)")
    return cams


def _write_cameras_file(cams: list) -> list[dict]:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    records = [c.__dict__ | {"extra": {}} for c in cams]  # drop bulky extra
    CAMERAS_FILE.write_text(json.dumps(records))
    os.chmod(CAMERAS_FILE, stat.S_IRUSR | stat.S_IWUSR)  # 600
    return records


def _run_on_demand_cmd(slug: str) -> str:
    py = shlex.quote(sys.executable)
    bridge = f"{py} -m baseus_bridge.bridge --camera $MTX_PATH"
    ff = (
        "ffmpeg -hide_banner -loglevel warning -fflags +genpts "
        f"-f h264 -framerate {FRAMERATE} -i - -c:v copy "
        "-f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$MTX_PATH"
    )
    return f"sh -c {shlex.quote(f'{bridge} | {ff}')}"


def _render_mediamtx_cfg(records: list[dict]) -> str:
    lines = [
        "# AUTO-GENERATED by baseus_bridge.orchestrator -- do not edit by hand.",
        "logLevel: info",
        f"rtspAddress: :{RTSP_PORT}",
        f"hlsAddress: :{HLS_PORT}",
        f"webrtcAddress: :{WEBRTC_PORT}",
        "rtmp: no",
        "srt: no",
        "hls: yes",
        "webrtc: yes",
        "paths:",
    ]
    for rec in records:
        slug = rec["slug"]
        cmd = _run_on_demand_cmd(slug)
        lines += [
            f"  {slug}:",
            f"    runOnDemand: {json.dumps(cmd)}",
            "    runOnDemandRestart: yes",
            "    runOnDemandStartTimeout: 20s",
            "    runOnDemandCloseAfter: 15s",
        ]
    lines.append("")
    return "\n".join(lines)


def serve():
    cams = discover()
    if not INCLUDE_OFFLINE:
        cams = [c for c in cams if c.online]
    if not cams:
        raise SystemExit("no cameras discovered (nothing to serve)")
    records = _write_cameras_file(cams)
    MEDIAMTX_CFG.write_text(_render_mediamtx_cfg(records))
    log(f"[serve] wrote {len(records)} path(s) to {MEDIAMTX_CFG}")
    for rec in records:
        status = "online" if rec["online"] else "OFFLINE"
        log(f"   rtsp://<host>:{RTSP_PORT}/{rec['slug']:<20} {rec['name']} [{status}]")
    log(f"[serve] starting MediaMTX ({MEDIAMTX_BIN})")
    os.execvp(MEDIAMTX_BIN, [MEDIAMTX_BIN, str(MEDIAMTX_CFG)])


def print_discovery():
    cams = discover()
    print(json.dumps([c.redacted() for c in cams], indent=2))
