"""Discover cameras from the Baseus cloud and serve them over RTSP/HLS/WebRTC.

Writes a runtime credentials file (mode 600) and a generated MediaMTX config,
then launches MediaMTX. Each camera is a MediaMTX path using ``runOnDemand`` so
the P2P bridge only runs while a client is connected -- important for battery
cameras. No secrets are ever written to the repo; only to the runtime dir.
"""
from __future__ import annotations

import json
import os
import re
import shlex
import stat
import sys
import time
from pathlib import Path

from .cloud import BaseusCloud

RUNTIME_DIR = Path(os.environ.get("BASEUS_RUNTIME_DIR", "/run/baseus"))
CAMERAS_FILE = Path(os.environ.get("BASEUS_CAMERAS_FILE", str(RUNTIME_DIR / "cameras.json")))
MEDIAMTX_CFG = Path(os.environ.get("BASEUS_MEDIAMTX_CFG", str(RUNTIME_DIR / "mediamtx.yml")))
MEDIAMTX_BIN = os.environ.get("MEDIAMTX_BIN", "mediamtx")

RTSP_PORT = os.environ.get("BASEUS_RTSP_PORT", "8554")
HLS_PORT = os.environ.get("BASEUS_HLS_PORT", "8888")
WEBRTC_PORT = os.environ.get("BASEUS_WEBRTC_PORT", "8889")
FRAMERATE = os.environ.get("BASEUS_FRAMERATE", "25")
INCLUDE_OFFLINE = os.environ.get("BASEUS_INCLUDE_OFFLINE", "1") not in ("0", "false", "no")

# Reliability / latency knobs.
# How long MediaMTX waits for the bridge to publish its first frame before
# killing it. Battery cameras can take a while to wake, so keep this generous.
START_TIMEOUT = os.environ.get("BASEUS_START_TIMEOUT", "60")
# How long to keep a stream running after the last viewer leaves. Higher =
# faster re-opens (stream stays warm) at the cost of more battery/bandwidth.
CLOSE_AFTER = os.environ.get("BASEUS_CLOSE_AFTER", "30")
# Always-on: keep every camera streaming from startup (instant load, best for
# mains-powered cameras). Off = on-demand (battery friendly).
ALWAYS_ON = os.environ.get("BASEUS_ALWAYS_ON", "0") not in ("0", "false", "no")


def log(*a):
    print(*a, file=sys.stderr, flush=True)


def _cloud_from_env() -> BaseusCloud:
    return BaseusCloud(
        account=os.environ.get("BASEUS_ACCOUNT", ""),
        password=os.environ.get("BASEUS_PASSWORD", ""),
        region=os.environ.get("BASEUS_REGION", "AUTO"),
        country_code=os.environ.get("BASEUS_COUNTRYCODE", "1"),
    )


def discover() -> list:
    cloud = _cloud_from_env()
    cloud.login()
    cams = cloud.discover_cameras()
    log(f"[cloud] logged in via {cloud.resolved_region}; found {len(cams)} camera(s)")
    return cams


def _write_cameras_file(cams: list) -> list[dict]:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    records = [c.__dict__ | {"extra": {}} for c in cams]  # drop bulky extra
    CAMERAS_FILE.write_text(json.dumps(records))
    os.chmod(CAMERAS_FILE, stat.S_IRUSR | stat.S_IWUSR)  # 600
    return records


def _run_on_demand_cmd(slug: str) -> str:
    py = shlex.quote(sys.executable)
    bridge = f"{py} -m baseus_bridge.bridge --camera $MTX_PATH"
    ff = (
        "ffmpeg -hide_banner -loglevel warning -fflags +genpts "
        "-analyzeduration 3M -probesize 3M "
        f"-f h264 -framerate {FRAMERATE} -i - -c:v copy "
        "-f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$MTX_PATH"
    )
    return f"sh -c {shlex.quote(f'{bridge} | {ff}')}"


def _render_mediamtx_cfg(records: list[dict]) -> str:
    lines = [
        "# AUTO-GENERATED by baseus_bridge.orchestrator -- do not edit by hand.",
        "logLevel: info",
        f"rtspAddress: :{RTSP_PORT}",
        f"hlsAddress: :{HLS_PORT}",
        f"webrtcAddress: :{WEBRTC_PORT}",
        "rtmp: no",
        "srt: no",
        "hls: yes",
        "webrtc: yes",
        # Give slow-waking cameras and RTSP readers more headroom.
        "readTimeout: 20s",
        "writeTimeout: 20s",
        "writeQueueSize: 1024",
        "paths:",
    ]
    for rec in records:
        slug = rec["slug"]
        cmd = _run_on_demand_cmd(slug)
        lines.append(f"  {slug}:")
        if ALWAYS_ON:
            # Keep the stream up from startup and restart it if it drops.
            lines += [
                f"    runOnInit: {json.dumps(cmd)}",
                "    runOnInitRestart: yes",
            ]
        else:
            lines += [
                f"    runOnDemand: {json.dumps(cmd)}",
                "    runOnDemandRestart: yes",
                f"    runOnDemandStartTimeout: {START_TIMEOUT}s",
                f"    runOnDemandCloseAfter: {CLOSE_AFTER}s",
            ]
    lines.append("")
    return "\n".join(lines)


def serve():
    # Retry initial discovery so a transient cloud/login hiccup doesn't take
    # the whole add-on down (Supervisor would otherwise just restart-loop it).
    cams = None
    last_err = None
    for attempt in range(1, 6):
        try:
            cams = discover()
            break
        except Exception as err:  # noqa: BLE001 - report and retry
            last_err = err
            wait = min(30, 5 * attempt)
            log(f"[serve] discovery attempt {attempt}/5 failed: {err}; retrying in {wait}s")
            time.sleep(wait)
    if cams is None:
        raise SystemExit(f"discovery failed after retries: {last_err}")
    if not INCLUDE_OFFLINE:
        cams = [c for c in cams if c.online]
    if not cams:
        raise SystemExit("no cameras discovered (nothing to serve)")
    records = _write_cameras_file(cams)
    MEDIAMTX_CFG.write_text(_render_mediamtx_cfg(records))
    log(f"[serve] wrote {len(records)} path(s) to {MEDIAMTX_CFG}")
    for rec in records:
        status = "online" if rec["online"] else "OFFLINE"
        log(f"   rtsp://<host>:{RTSP_PORT}/{rec['slug']:<20} {rec['name']} [{status}]")
    log(f"[serve] starting MediaMTX ({MEDIAMTX_BIN})")
    os.execvp(MEDIAMTX_BIN, [MEDIAMTX_BIN, str(MEDIAMTX_CFG)])


def print_discovery():
    cams = discover()
    print(json.dumps([c.redacted() for c in cams], indent=2))


# Keys whose *values* are credentials/identifiers and must never be printed.
_SENSITIVE_KEY = re.compile(
    r"(pass|pwd|token|auth|secret|p2p|(?<![a-z])key(?![a-z])|licen|access|"
    r"refresh|session|cookie|sign(?!al)|ticket|account|email|phone|mobile|"
    r"user_?id|userid|(?<![a-z])uid(?![a-z])|nickname|share_name|"
    r"(?<![a-z])did(?![a-z])|(?<![a-z])sn(?![a-z])|serial|(?<![a-z])mac|"
    r"(?<![a-z])ip(?![a-z])|(?<![a-z])lan|(?<![a-z])wan|ssid)",
    re.I,
)
# Value-level catch-all: anything that looks like an email address.
_EMAIL_VALUE = re.compile(r"[^\s@]+@[^\s@]+\.[^\s@]+")


def _redact(obj):
    """Recursively mask sensitive values while preserving all keys/structure."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if isinstance(v, (dict, list)):
                out[k] = _redact(v)
            elif _SENSITIVE_KEY.search(str(k)):
                out[k] = "***"
            elif isinstance(v, str) and _EMAIL_VALUE.fullmatch(v.strip()):
                out[k] = "***"
            else:
                out[k] = v
        return out
    if isinstance(obj, list):
        return [_redact(v) for v in obj]
    return obj


def print_raw_devices():
    """Print the full cloud device-list JSON with sensitive values redacted.

    Useful for mapping which sensors/controls a camera model exposes without
    leaking credentials or identifiers into logs.
    """
    cloud = _cloud_from_env()
    cloud.login()
    resp = cloud.raw_device_list()
    print(json.dumps(_redact(resp), indent=2, ensure_ascii=False))


def _iter_devices(resp: dict):
    return ((resp.get("payload") or {}).get("device_list")) or []


def _first_base_led(resp: dict):
    """Return (device_sn, led_status) for the first device that reports an LED."""
    for dev in _iter_devices(resp):
        info = dev.get("device_info") or {}
        if info.get("led_status") is not None:
            return dev.get("device_sn"), info.get("led_status")
    return None, None


def _first_child_probe(resp: dict, key: str):
    """Return (base_sn, channel, child_sn, value) for the first child with ``key``."""
    for dev in _iter_devices(resp):
        info = dev.get("device_info") or {}
        chans = {c.get("sn"): c.get("channel") for c in (info.get("CameraChannel") or [])}
        for child in (dev.get("child_list") or []):
            ci = child.get("child_info") or {}
            if ci.get(key) is not None:
                csn = child.get("child_sn")
                return dev.get("device_sn"), int(chans.get(csn, 0) or 0), csn, ci.get(key)
    return None, None, None, None


def _read_child_val(resp: dict, child_sn: str, key: str):
    for dev in _iter_devices(resp):
        for child in (dev.get("child_list") or []):
            if child.get("child_sn") == child_sn:
                return (child.get("child_info") or {}).get(key)
    return None


def _probe_pair(cloud, label, key, current, set_kwargs, read_val, samples):
    """Try every action/shape to flip ``key``, verify, then revert.

    ``set_kwargs(action, shape, value)`` -> dict for ``set_device_param``.
    ``read_val()`` -> freshly re-read current value (or None).
    Appends per-attempt outcomes to ``samples`` for diagnostics.
    Returns (action, shape) that verifiably changed the value, else None.
    """
    from .cloud import SET_ACTION_CANDIDATES, SET_SHAPE_CANDIDATES

    target = 0 if current else 1
    log(f"[probe] {label}: current={current}, trying -> {target}")
    for action in SET_ACTION_CANDIDATES:
        for shape in SET_SHAPE_CANDIDATES:
            try:
                accepted, resp = cloud.set_device_param(**set_kwargs(action, shape, target))
            except Exception as err:  # noqa: BLE001
                samples.append({"level": label, "action": action, "shape": shape,
                                "error": str(err)[:120]})
                continue
            samples.append({
                "level": label, "action": action, "shape": shape,
                "accepted": accepted, "code": resp.get("code"),
                "msg": (resp.get("msg") or resp.get("message")
                        or resp.get("_text") or "")[:120],
                "http": resp.get("_http"),
            })
            if not accepted:
                continue
            log(f"[probe] {label} {action}/{shape}: ACCEPTED (code={resp.get('code')}); verifying...")
            val = None
            for _ in range(3):
                time.sleep(2)
                val = read_val()
                if val is not None:
                    break
            if val == target:
                log(f"[probe] {label} VERIFIED with {action}/{shape}; reverting to {current}")
                try:
                    cloud.set_device_param(**set_kwargs(action, shape, current))
                except Exception:  # noqa: BLE001
                    log(f"[probe] WARNING: {label} revert failed; restore it in the app")
                return action, shape
            log(f"[probe] {label} {action}/{shape}: accepted but no change; skipping")
    return None


def _summarize_samples(samples):
    """Dedupe probe responses by (accepted, http, code, msg/error) for readability."""
    buckets: dict = {}
    for s in samples:
        keyt = (s.get("accepted"), s.get("http"), s.get("code"),
                s.get("msg", s.get("error", "")))
        b = buckets.setdefault(keyt, {"count": 0, "examples": []})
        b["count"] += 1
        if len(b["examples"]) < 3:
            b["examples"].append(f"{s['action']}/{s['shape']}")
    out = []
    for (accepted, http, code, msg), b in buckets.items():
        out.append({"accepted": accepted, "http": http, "code": code,
                    "msg": msg, "count": b["count"], "examples": b["examples"]})
    return sorted(out, key=lambda d: -d["count"])


def probe_controls():
    """Safely discover the cloud 'set' Action + body shape for this account.

    Non-destructive: probes the benign HomeStation **status LED** (base level)
    and the cosmetic **OSD logo** overlay (child/per-camera level), verifying
    each change by re-reading the device list and then reverting it. Wrong
    action/shape combos simply error or no-op, so nothing is left changed.
    Prints the confirmed pairs to pin in Home Assistant (or via env).
    """
    cloud = _cloud_from_env()
    cloud.login()
    samples: list = []

    # --- base level: status LED ---
    base_sn, led = _first_base_led(cloud.raw_device_list())
    base_winner = None
    if base_sn is None:
        log("[probe] no base 'led_status' to probe; skipping base level")
    else:
        base_winner = _probe_pair(
            cloud, "base/led_status", "led_status", led,
            set_kwargs=lambda a, s, v: dict(device_sn=base_sn, key="led_status",
                                            value=v, action=a, shape=s),
            read_val=lambda: _first_base_led(cloud.raw_device_list())[1],
            samples=samples,
        )

    # --- child level: OSD logo overlay (cosmetic, fully reversible) ---
    b_sn, ch, child_sn, osd = _first_child_probe(cloud.raw_device_list(), "osd_logo")
    child_winner = None
    if child_sn is None:
        log("[probe] no child 'osd_logo' to probe; skipping child level")
    else:
        child_winner = _probe_pair(
            cloud, "child/osd_logo", "osd_logo", osd,
            set_kwargs=lambda a, s, v: dict(device_sn=b_sn, key="osd_logo", value=v,
                                            action=a, shape=s, channel=ch, child_sn=child_sn),
            read_val=lambda: _read_child_val(cloud.raw_device_list(), child_sn, "osd_logo"),
            samples=samples,
        )

    out = {
        "diagnostics": _summarize_samples(samples),
        "base": {
            "confirmed_action": base_winner[0] if base_winner else None,
            "confirmed_shape": base_winner[1] if base_winner else None,
        },
        "child": {
            "confirmed_action": child_winner[0] if child_winner else None,
            "confirmed_shape": child_winner[1] if child_winner else None,
        },
    }
    if child_winner or base_winner:
        out["hint"] = (
            "In HA -> Baseus Security -> Configure: enable controls and paste the "
            "CHILD action/shape (covers the per-camera switches). If the base pair "
            "differs, set it too for the HomeStation LED."
        )
    else:
        codes = {d.get("code") for d in out["diagnostics"]}
        if codes == {-9999}:
            out["hint"] = (
                "the cloud rejected every write with -9999 'interface not "
                "currently supported' -> this cloud gateway is read-only; "
                "settings would need local P2P set-commands (not implemented)"
            )
        else:
            out["hint"] = (
                "no working set-action found with the tried conventions; per-device "
                "controls likely require deeper protocol work (see diagnostics)"
            )
    print(json.dumps(out, indent=2))
